// Auto-generated by LibreLane
module FMD_QNC_Padframe28(
`ifdef USE_POWER_PINS
  inout IO_CORNER_NORTH_WEST_INST.iovdd_RING,
  inout IO_CORNER_NORTH_WEST_INST.iovss_RING,
  inout IO_CORNER_NORTH_WEST_INST.vdd_RING,
  inout IO_CORNER_NORTH_WEST_INST.vss_RING,
  inout VSS,
  inout VDD,
`endif
  inout[11:0] ui_PAD,
  inout[11:0] uo_PAD
);
endmodule
